"""Velum Streamlit frontend."""

from __future__ import annotations

import base64
from html import escape
from pathlib import Path

import httpx
import streamlit as st
import streamlit.components.v1 as components

# --- Configuration ---
# Hard-coded local backend URL - Velum is local-first; see AGENTS.md section 10.
BACKEND_URL = "http://127.0.0.1:8000"

# Bundled brand assets (shipped via [tool.hatch.build.targets.wheel.force-include]).
_STATIC_DIR = Path(__file__).parent / "static"
# Vector mark — single SVG with embedded `prefers-color-scheme` styles so the
# fill switches between white (#FFFFFF) on dark surfaces and slate (#1E293B) on
# light. Generated by tracing assets/branding/_mark.png with vtracer; see
# scripts/generate_branding.py for the regeneration pipeline.
_MARK_PATH = _STATIC_DIR / "mark.svg"
_FAVICON_PATH = _MARK_PATH
_LOGO_PATH = _MARK_PATH


def _logo_data_uri() -> str | None:
    """Return the bundled logo encoded as a data: URI, or None if missing."""
    if not _LOGO_PATH.exists():
        return None
    svg = _LOGO_PATH.read_text(encoding="utf-8")
    encoded = base64.b64encode(svg.encode("utf-8")).decode("ascii")
    return f"data:image/svg+xml;base64,{encoded}"

# PII category colors (light mode values; dark mode handled via CSS)
CATEGORY_COLORS: dict[str, dict[str, str]] = {
    "private_person": {"light": "#EC4899", "dark": "#F472B6", "label": "Person"},
    "private_email": {"light": "#10B981", "dark": "#34D399", "label": "Email"},
    "private_phone": {"light": "#F59E0B", "dark": "#FBBF24", "label": "Phone"},
    "private_address": {"light": "#8B5CF6", "dark": "#A78BFA", "label": "Address"},
    "private_date": {"light": "#06B6D4", "dark": "#22D3EE", "label": "Date"},
    "private_url": {"light": "#3B82F6", "dark": "#60A5FA", "label": "URL"},
    "account_number": {"light": "#EF4444", "dark": "#F87171", "label": "Account"},
    "secret": {"light": "#6B7280", "dark": "#9CA3AF", "label": "Secret"},
}

_DEFAULT_COLORS = {"light": "#6B7280", "dark": "#9CA3AF", "label": "Other"}


def inject_custom_css() -> None:
    """Inject custom CSS for the polished SaaS theme with OS-adaptive light/dark mode."""
    st.markdown(
        """
        <style>
        @import url('https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@300;400;500;600;700&display=swap');

        /* Base styles */
        html, body, [class*="css"] {
            font-family: 'Plus Jakarta Sans', sans-serif;
        }

        /* Light mode (default) — page is soft slate, cards are pure white,
           subtle shadow gives depth (Linear/Vercel pattern). */
        :root {
            --bg-primary: #F8FAFC;
            --bg-surface: #FFFFFF;
            --border-color: #E2E8F0;
            --text-primary: #0F172A;
            --text-secondary: #475569;
            --accent: #6366F1;
            --accent-hover: #4F46E5;
            --success: #10B981;
            --card-shadow: 0 1px 2px rgba(15, 23, 42, 0.04),
                0 1px 3px rgba(15, 23, 42, 0.06);
        }

        /* Apply page background to Streamlit's main container */
        .stApp,
        [data-testid="stAppViewContainer"] {
            background: var(--bg-primary);
        }

        /* Wide layout: cap content width so lines stay readable on huge screens
           while still giving way more horizontal space than Streamlit's
           default centered layout (~704px). */
        [data-testid="stMainBlockContainer"],
        .block-container {
            max-width: 1200px !important;
            padding-left: 32px !important;
            padding-right: 32px !important;
        }

        /* Dark mode (auto from OS) */
        @media (prefers-color-scheme: dark) {
            :root {
                --bg-primary: #0F172A;
                --bg-surface: #1E293B;
                --border-color: #334155;
                --text-primary: #F8FAFC;
                --text-secondary: #94A3B8;
                --accent: #818CF8;
                --accent-hover: #6366F1;
                --success: #34D399;
                --card-shadow: none;
            }
        }

        /* Header styling */
        .velum-header {
            display: flex;
            align-items: center;
            justify-content: space-between;
            padding: 16px 0;
            margin-bottom: 24px;
            border-bottom: 1px solid var(--border-color);
        }
        .velum-header h1 {
            font-size: 24px;
            font-weight: 700;
            color: var(--text-primary);
            margin: 0;
        }
        .velum-brand {
            display: inline-flex;
            align-items: center;
            gap: 12px;
        }
        .velum-brand img {
            width: 64px;
            height: 64px;
            display: block;
            /* Mark colour is theme-adaptive via `prefers-color-scheme` rules
               embedded inside mark.svg itself — no CSS filter needed here. */
        }
        .velum-status {
            display: inline-flex;
            align-items: center;
            gap: 8px;
            padding: 6px 12px;
            border-radius: 20px;
            font-size: 13px;
            font-weight: 500;
            background: var(--bg-surface);
            border: 1px solid var(--border-color);
            color: var(--text-secondary);
        }
        .velum-status .dot {
            width: 8px;
            height: 8px;
            border-radius: 50%;
            background: var(--success);
        }

        /* Result card */
        .result-card {
            background: var(--bg-surface);
            border: 1px solid var(--border-color);
            border-radius: 12px;
            padding: 24px;
            margin: 16px 0;
            color: var(--text-primary);
            line-height: 1.6;
            white-space: pre-wrap;
            word-wrap: break-word;
            box-shadow: var(--card-shadow);
        }
        .result-card.is-mono {
            font-family: ui-monospace, SFMono-Regular, "SF Mono", Menlo,
                Consolas, "Liberation Mono", monospace;
            font-size: 13.5px;
        }

        /* Editable redacted output — style the textarea to match .result-card.
           Streamlit wraps the textarea in a div that gets a red border on focus;
           we override both the wrapper and the textarea itself. */
        div[data-testid="stTextArea"]:has(textarea[aria-label="Redacted output (editable)"]) > div,
        div[data-baseweb="textarea"]:has(textarea[aria-label="Redacted output (editable)"]) {
            border-color: var(--border-color) !important;
            box-shadow: none !important;
        }
        div[data-testid="stTextArea"]:focus-within:has(
            textarea[aria-label="Redacted output (editable)"]
        ) > div,
        div[data-baseweb="textarea"]:focus-within:has(
            textarea[aria-label="Redacted output (editable)"]
        ) {
            border-color: var(--accent) !important;
            box-shadow: 0 0 0 1px var(--accent) !important;
        }
        textarea[aria-label="Redacted output (editable)"] {
            background: var(--bg-surface) !important;
            border: 1px solid var(--border-color) !important;
            border-radius: 12px !important;
            padding: 24px !important;
            color: var(--text-primary) !important;
            font-family: ui-monospace, SFMono-Regular, "SF Mono", Menlo,
                Consolas, "Liberation Mono", monospace !important;
            font-size: 13.5px !important;
            line-height: 1.6 !important;
            outline: none !important;
            caret-color: var(--accent) !important;
            box-shadow: var(--card-shadow) !important;
        }
        textarea[aria-label="Redacted output (editable)"]:focus,
        textarea[aria-label="Redacted output (editable)"]:focus-visible {
            border-color: var(--accent) !important;
            box-shadow: 0 0 0 1px var(--accent) !important;
            outline: none !important;
        }

        /* PII highlight spans — entity text + category tag chip (Gradio-style) */
        .pii-highlight {
            display: inline-flex;
            align-items: center;
            gap: 6px;
            padding: 2px 4px 2px 8px;
            border-radius: 6px;
            font-weight: 500;
            font-size: 14px;
            line-height: 1.4;
            white-space: nowrap;
        }
        .pii-label {
            display: inline-block;
            padding: 1px 6px;
            border-radius: 4px;
            font-family: ui-monospace, SFMono-Regular, "SF Mono", Menlo,
                Consolas, "Liberation Mono", monospace;
            font-size: 10.5px;
            font-weight: 700;
            letter-spacing: 0.04em;
            color: #FFFFFF;
        }

        /* Legend */
        .legend {
            display: flex;
            flex-wrap: wrap;
            gap: 12px;
            margin: 12px 0;
        }
        .legend-item {
            display: inline-flex;
            align-items: center;
            gap: 6px;
            font-size: 13px;
            color: var(--text-secondary);
        }
        .legend-dot {
            width: 10px;
            height: 10px;
            border-radius: 50%;
        }

        /* Footer */
        .velum-footer {
            margin-top: 48px;
            padding-top: 16px;
            border-top: 1px solid var(--border-color);
            text-align: center;
            font-size: 12px;
            color: var(--text-secondary);
        }

        /* Primary button — override Streamlit's default red with brand indigo */
        .stButton > button[kind="primary"],
        div[data-testid="stBaseButton-primary"],
        button[data-testid="baseButton-primary"] {
            background-color: var(--accent) !important;
            border-color: var(--accent) !important;
            color: #FFFFFF !important;
        }
        .stButton > button[kind="primary"]:hover,
        div[data-testid="stBaseButton-primary"]:hover,
        button[data-testid="baseButton-primary"]:hover {
            background-color: var(--accent-hover) !important;
            border-color: var(--accent-hover) !important;
        }

        /* Hide Streamlit branding */
        #MainMenu {visibility: hidden;}
        footer {visibility: hidden;}
        header {visibility: hidden;}

        /* Hide Streamlit's auto-generated heading anchor links (the chain icon
           that appears on hover next to every <h1>/<h2>/etc.) — they're meant
           for deep-linking long docs and add noise on a single-page app. */
        h1 a, h2 a, h3 a, h4 a, h5 a, h6 a,
        [data-testid="stHeaderActionElements"],
        [data-testid="stMarkdownContainer"] a.anchor-link {
            display: none !important;
        }
        </style>
        """,
        unsafe_allow_html=True,
    )


def check_backend_health() -> dict | None:
    """Check if the backend is healthy.

    Returns:
        Parsed JSON response from /health, or None if the backend is unreachable.
    """
    try:
        response = httpx.get(f"{BACKEND_URL}/health", timeout=5.0)
        if response.status_code == 200:
            return response.json()
    except httpx.ConnectError:
        return None
    except httpx.HTTPError:
        return None
    return None


def call_redact_api(text: str) -> dict | None:
    """Call the backend /redact endpoint.

    Args:
        text: Input text to redact.

    Returns:
        Parsed JSON response, or None on connection / HTTP error (with st.error displayed).
    """
    try:
        response = httpx.post(
            f"{BACKEND_URL}/redact",
            json={"text": text},
            timeout=60.0,
        )
        if response.status_code == 200:
            return response.json()
        st.error(f"Backend error: {response.status_code} - {response.text}")
        return None
    except httpx.ConnectError:
        st.error("Cannot connect to backend. Is it running?")
        return None


def render_highlighted_text(original: str, spans: list[dict]) -> str:
    """Build HTML with highlighted PII spans.

    All user-controlled text is escaped via ``html.escape`` before being placed in
    the rendered HTML; category colors come from a fixed allow-list and are safe.

    Args:
        original: The original text containing PII.
        spans: List of span dicts with start/end/category/text fields.

    Returns:
        An HTML string with PII spans wrapped in styled ``<span>`` elements.
    """
    if not spans:
        return escape(original)

    html_parts: list[str] = []
    cursor = 0

    for span in sorted(spans, key=lambda s: s["start"]):
        start = span["start"]
        end = span["end"]

        # Text before the span (escaped)
        if cursor < start:
            html_parts.append(escape(original[cursor:start]))

        # The highlighted span (text and category escaped; colors from allow-list)
        category = span["category"]
        colors = CATEGORY_COLORS.get(category, _DEFAULT_COLORS)
        bg_light = colors["light"] + "20"  # ~12% opacity background
        border_light = colors["light"] + "40"
        span_text = escape(span.get("text", original[start:end]))
        tag_text = escape(category.upper())
        html_parts.append(
            f'<span class="pii-highlight" '
            f'style="background: {bg_light}; '
            f'color: {colors["light"]}; '
            f'border: 1px solid {border_light};">'
            f"{span_text}"
            f'<span class="pii-label" style="background: {colors["light"]};">'
            f"{tag_text}</span>"
            f"</span>"
        )
        cursor = end

    # Remaining text (escaped)
    if cursor < len(original):
        html_parts.append(escape(original[cursor:]))

    return "".join(html_parts)


def render_legend(spans: list[dict]) -> str:
    """Build HTML legend for the categories detected in this result.

    Args:
        spans: List of span dicts with at least a ``category`` field.

    Returns:
        An HTML string for the legend, or empty string if no categories.
    """
    categories = {s["category"] for s in spans}
    if not categories:
        return ""

    items: list[str] = []
    for cat in sorted(categories):
        colors = CATEGORY_COLORS.get(cat, _DEFAULT_COLORS)
        label = escape(colors.get("label", cat))
        items.append(
            f'<span class="legend-item">'
            f'<span class="legend-dot" style="background: {colors["light"]};"></span>'
            f"{label}"
            f"</span>"
        )
    return f'<div class="legend">{"".join(items)}</div>'


def main() -> None:
    """Main Streamlit app entry point."""
    st.set_page_config(
        page_title="Velum",
        page_icon=str(_FAVICON_PATH) if _FAVICON_PATH.exists() else None,
        layout="wide",
    )

    inject_custom_css()

    # Header
    health = check_backend_health()
    status_text = "Ready" if health else "Connecting..."
    logo_uri = _logo_data_uri()
    logo_html = f'<img src="{logo_uri}" alt="Velum logo" />' if logo_uri else ""
    st.markdown(
        f"""
        <div class="velum-header">
            <span class="velum-brand">
                {logo_html}
                <h1>Velum</h1>
            </span>
            <span class="velum-status">
                <span class="dot"></span>
                {escape(status_text)}
            </span>
        </div>
        """,
        unsafe_allow_html=True,
    )

    # Show loading state if backend not ready
    if not health:
        st.info(
            "Waiting for the backend to start. "
            "The model may be downloading (first run only)..."
        )
        st.stop()

    # Input section
    st.markdown("#### Enter text to redact")
    placeholder_text = (
        "My name is Alice Smith and my email is alice@example.com. "
        "I live at 123 Main St and my phone is 555-0123."
    )
    text_input = st.text_area(
        label="Input text",
        placeholder=placeholder_text,
        height=200,
        label_visibility="collapsed",
    )

    # Redact button (centered)
    _, col_btn, _ = st.columns([4, 2, 4])
    with col_btn:
        redact_clicked = st.button("Redact", type="primary", use_container_width=True)

    # Results — persist across reruns (e.g. download button click triggers a rerun)
    if redact_clicked:
        if not text_input:
            st.warning("Please enter some text to redact.")
            st.session_state.pop("last_result", None)
        else:
            with st.spinner("Analyzing..."):
                result = call_redact_api(text_input)
            if result:
                st.session_state["last_result"] = result

    result = st.session_state.get("last_result")
    if result:
        st.markdown("---")

        # Detected PII section
        st.markdown("#### Detected PII")
        highlighted_html = render_highlighted_text(result["original"], result["spans"])
        st.markdown(
            f'<div class="result-card">{highlighted_html}</div>',
            unsafe_allow_html=True,
        )

        # Legend
        legend_html = render_legend(result["spans"])
        if legend_html:
            st.markdown(legend_html, unsafe_allow_html=True)

        # Redacted output — editable text area styled to match .result-card
        st.markdown("#### Redacted Output")
        # Auto-size to content (rough heuristic: ~80 chars per line, 24px per line, min 200)
        line_count = max(result["redacted"].count("\n") + 1, len(result["redacted"]) // 80)
        textarea_height = max(200, min(600, line_count * 24 + 48))
        edited = st.text_area(
            label="Redacted output (editable)",
            value=result["redacted"],
            height=textarea_height,
            key="redacted_editable",
            label_visibility="collapsed",
        )

        # Action buttons — Copy + Download
        _, col_copy, col_download, _ = st.columns([2, 2, 2, 2])
        with col_copy:
            # Copy button reads the live textarea value (so edits are captured) and
            # writes to the clipboard. Falls back to execCommand on insecure contexts.
            components.html(
                """
                <button id="velum-copy-btn" onclick="(function(btn){
                    const doc = window.parent.document;
                    const sel = 'textarea[aria-label=\\'Redacted output (editable)\\']';
                    const ta = doc.querySelector(sel);
                    if (!ta) { btn.innerText = 'Not found'; return; }
                    const text = ta.value;
                    const done = () => {
                        btn.innerText = 'Copied';
                        setTimeout(() => { btn.innerText = 'Copy'; }, 1500);
                    };
                    if (navigator.clipboard && window.isSecureContext) {
                        navigator.clipboard.writeText(text).then(done).catch(() => {
                            ta.select(); doc.execCommand('copy'); done();
                        });
                    } else {
                        ta.select(); doc.execCommand('copy'); done();
                    }
                })(this);">Copy</button>
                <style>
                    /* Light mode (default) — matches project palette in inject_custom_css */
                    :root {
                        --vc-bg: #FFFFFF;
                        --vc-surface: #F8FAFC;
                        --vc-border: #E2E8F0;
                        --vc-text: #1E293B;
                        --vc-accent: #6366F1;
                        --vc-accent-hover: #4F46E5;
                    }
                    @media (prefers-color-scheme: dark) {
                        :root {
                            --vc-bg: #0F172A;
                            --vc-surface: #1E293B;
                            --vc-border: #334155;
                            --vc-text: #F8FAFC;
                            --vc-accent: #818CF8;
                            --vc-accent-hover: #6366F1;
                        }
                    }
                    html, body {
                        margin: 0;
                        padding: 0;
                        background: transparent;
                        overflow: hidden;
                    }
                    #velum-copy-btn {
                        width: 100%;
                        padding: 8px 16px;
                        font-family: 'Plus Jakarta Sans',
                            -apple-system, BlinkMacSystemFont, sans-serif;
                        font-size: 14px;
                        font-weight: 500;
                        border-radius: 8px;
                        cursor: pointer;
                        background: var(--vc-surface);
                        color: var(--vc-text);
                        border: 1px solid var(--vc-border);
                        transition: background 200ms, border-color 200ms,
                            color 200ms;
                    }
                    #velum-copy-btn:hover {
                        background: var(--vc-accent);
                        border-color: var(--vc-accent);
                        color: #FFFFFF;
                    }
                    #velum-copy-btn:active {
                        background: var(--vc-accent-hover);
                        border-color: var(--vc-accent-hover);
                    }
                </style>
                """,
                height=38,
            )
        with col_download:
            st.download_button(
                label="Download",
                data=edited,
                file_name="redacted.txt",
                mime="text/plain",
                use_container_width=True,
            )

    # How to read results — placed near the bottom so it doesn't compete with
    # the primary input/redact flow. Collapsed by default; sets honest
    # expectations about the tool's scope and limits. Kept in sync with the
    # public README's "What it detects" section.
    with st.expander("How to read results"):
        st.markdown(
            """
- Detects **8 model categories**: person, email, phone, address, date,
  URL, account number, and secrets.
- A **deterministic regex backstop** also flags specific credential
  patterns as secrets even if the model misses them: AWS access keys
  (`AKIA…`), GitHub PATs (`ghp_…`, `github_pat_…`),
  OpenAI / Anthropic keys (`sk-…`), Google API keys (`AIza…`),
  and Slack tokens (`xoxb-…`, `xoxp-…`).
- Each detection is shown highlighted in the original text with a label
  chip (e.g. `PRIVATE_PERSON`), and replaced with a placeholder in the
  redacted output.
- Best treated as a **redaction aid**, not a standalone compliance or
  anonymization guarantee — always review the output before sharing.
- The underlying model has **strongest support for English**; results on
  other languages may be less reliable.
- Everything runs **locally** on your machine. No text leaves your computer.
            """
        )

    # Footer
    model_name = health.get("model", "unknown") if health else "unknown"
    device = health.get("device", "unknown") if health else "unknown"
    st.markdown(
        f"""
        <div class="velum-footer">
            Velum v0.1.0 &middot; {escape(model_name)} &middot; {escape(device)}
        </div>
        """,
        unsafe_allow_html=True,
    )


if __name__ == "__main__":
    main()
